# Generated by Django 5.0 on 2023-12-30 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="position",
            field=models.CharField(
                blank=True, default=django.utils.timezone.now, max_length=150
            ),
            preserve_default=False,
        ),
    ]
